version: '3.9'
volumes:
  postgres_data:
  pgadmin:
  rabbitmq_data:

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    volumes:
      - 'rabbitmq_data:/data'
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=${AMQP_USER:-user}
      - RABBITMQ_DEFAULT_PASS=${AMQP_PASS:-pass}
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 3